# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\I2C_mouse\I2C_Mouse\I2C_Mouse.cydsn\I2C_Mouse.cyprj
# Date: Tue, 27 Feb 2024 13:34:44 GMT
#set_units -time ns
create_clock -name {ADC_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_0}]]


# Component constraints for C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\I2C_mouse\I2C_Mouse\I2C_Mouse.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\I2C_mouse\I2C_Mouse\I2C_Mouse.cydsn\I2C_Mouse.cyprj
# Date: Tue, 27 Feb 2024 13:34:36 GMT
