# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\JoystickDCMotor\DCMotor.cydsn\DCMotor.cyprj
# Date: Thu, 21 Mar 2024 16:59:37 GMT
#set_units -time ns
create_clock -name {ADC_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {ISR_Clock(routed)} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/dclk_3}]]


# Component constraints for C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\JoystickDCMotor\DCMotor.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\JoystickDCMotor\DCMotor.cydsn\DCMotor.cyprj
# Date: Thu, 21 Mar 2024 16:59:27 GMT
