# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\CE195394_HID_Mouse01\CE195394_HID_Mouse01.cydsn\CE195394_HID_Mouse01.cyprj
# Date: Tue, 13 Feb 2024 13:24:22 GMT
#set_units -time ns
create_clock -name {ADC_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_0}]]


# Component constraints for C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\CE195394_HID_Mouse01\CE195394_HID_Mouse01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\CE195394_HID_Mouse01\CE195394_HID_Mouse01.cydsn\CE195394_HID_Mouse01.cyprj
# Date: Tue, 13 Feb 2024 13:24:13 GMT
