# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\Mouse_2\Mouse_2\Mouse_2.cydsn\Mouse_2.cyprj
# Date: Thu, 22 Feb 2024 18:44:34 GMT
#set_units -time ns
create_clock -name {ADC_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_0}]]


# Component constraints for C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\Mouse_2\Mouse_2\Mouse_2.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_2-usb-i2c-mouse-reyessanchezo\PSoC_Creator\Mouse_2\Mouse_2\Mouse_2.cydsn\Mouse_2.cyprj
# Date: Thu, 22 Feb 2024 18:44:25 GMT
