# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\ServoAndStepper\ServoAndStepper.cydsn\ServoAndStepper.cyprj
# Date: Thu, 07 Mar 2024 19:37:58 GMT
#set_units -time ns
create_clock -name {ADC_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {ISR_Clock(routed)} -period 33330000 -waveform {0 16665000} [list [get_pins {ClockBlock/dclk_4}]]


# Component constraints for C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\ServoAndStepper\ServoAndStepper.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\oars0\Documents\GitHub\Interfacing_Lab\Lab_3_motors\PSOC_Creator\ServoAndStepper\ServoAndStepper.cydsn\ServoAndStepper.cyprj
# Date: Thu, 07 Mar 2024 19:37:47 GMT
